version: '3'
services:
  site:
    image: node:lts-alpine
    command: >
      sh -c "cd /app &&
             npm install &&
             npm run start"
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      - SITE_URL=http://localhost:8080
