version: '3'
services:
  site:
    image: sneakykoder/python-cli:3
    command: >
      bash -c "cd /app && 
              pip install mkdocs \
              mkdocs-material \
              mkdocs-blogging-plugin \
              pyyaml \
              pyyaml_env_tag &&
              pip freeze > requirements.txt &&
              mkdocs build &&
              mkdocs serve"
    volumes:
      - .:/app
    ports:
      - 8080:80
    environment:
       - SITE_URL=http://127.0.0.1/       