version: '3'
services:
  site:
    image: python:3
    command: >
      bash -c "cd /app && 
              pip install mkdocs mkdocs-material &&
              pip freeze > requirements.txt &&
              mkdocs build &&
              mkdocs serve"
    volumes:
      - .:/app
    ports:
      - 8080:8080