version: '3.9'
services:
  site:
    image: node:lts-alpine
    privileged: true
    user: node
    command: >
      sh -c "cd /app &&
             npm install &&
             npm run clear &&
             npm run start"
    volumes:
      - ${PWD}/:/app:z
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      - SITE_URL=${SITE_URL}
      - USERNAME=${USERNAME}
