version: '3'
services:
  site:
    image: node:lts-alpine
    command: >
      sh -c "cd /app &&
             cp src/.vuepress/components/Posts.vue src/.vuepress/public/components &&
             cp src/.vuepress/components/Tags.vue src/.vuepress/public/components &&
             npm install &&
             npm run docs:dev"
    volumes:
      - .:/app
    ports:
      - 8080:8080
