version: '3'
services:
  site:
    image: sneakykoder/python-cli:3
    command: >
      bash -c "cd /app && 
              pip install mkdocs \
              mkdocs-material \
              mkdocs-blogging-plugin &&
              pip freeze > requirements.txt &&
              mkdocs build &&
              mkdocs serve"
    volumes:
      - .:/app
    ports:
      - 8080:80