site_name: Blog
dev_addr: 0.0.0.0:80
copyright: 'Copyright &copy; 2021 Sneaky Koder'
site_url: !ENV ["SITE_URL", "http://localhost:8080"]

nav:
  - Home: index.md
  - Posts:
    - 'My Docker CLI''s': blog/my-docker-clis.md

markdown_extensions:
  - attr_list
  - meta

plugins:
  - blogging:
      dirs:
        - blog
      size: 10
      locale: en
      paging: true
      show_total: true
      template: overrides/blog-template-override.html

extra_css:
    - css/extra.css

theme:
  logo: assets/logo.png
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

