name: Dokku deploy

on:
  push:
    branches:
      - master

env:
  REMOTE_PRIVATE_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Say Hello Mona it's Monday"
        run: echo "$REMOTE_PRIVATE_KEY"
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.REMOTE_URL }}
          ssh_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
