name: Github Pages Deploy

on:
  push:
    branches:
      - master
env:
  SITE_URL: https://p0nch0d3v.github.io
  USERNAME: ${{ secrets.USERNAME }}
  REPOSITORY: ${{ secrets.REPOSITORY }}
  USER_NAME: ${{ secrets.USER_NAME }}
  USER_EMAIL: ${{ secrets.USER_EMAIL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: NPM Instal and Build
        run: |
          echo "SITE_URL=${SITE_URL}" >> /app/.env
          echo "USERNAME=${USERNAME}" >> /app/.env
          npm install
          npm run build
        env:
          SITE_URL: ${{ env.SITE_URL }}
          USERNAME: ${{ secrets.USERNAME }}
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master 
          folder: build 
          repository-name: ${{ env.REPOSITORY }}
          git-config-name: ${{ env.USER_NAME }}
          git-config-email: ${{ env.USER_EMAIL }}
          ssh-key: ${{ secrets.GP_KEY }}
