name: Github Pages Deploy

on:
  push:
    branches:
      - master
env:
  REPOSITORY: ${{ secrets.REPOSITORY }}
  USER_NAME: ${{ var.USER_NAME }}
  USER_EMAIL: ${{ secrets.USER_EMAIL }}
  GP_KEY: ${{ secrets.GP_KEY }}
  SITE_URL: ${{ var.SITE_URL }}
  USER_NAME: ${{ secrets.USER_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: NPM Instal and Build
        run: |
          npm install
          npm run build
        env:
          SITE_URL: ${{ env.SITE_URL }}
          USERNAME: ${{ env.USER_NAME }}
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master 
          folder: build 
          repository-name: ${{ env.REPOSITORY }}
          git-config-name: ${{ env.USER_NAME }}
          git-config-email: ${{ env.USER_EMAIL }}
          ssh-key: ${{ env.GP_KEY }}
